.bookignore
package-lock.json
package.json
publish-gh-pages.sh

- Added publish script. The script will publish the current active branch to gh-pages, and switch back to the current branch.
- Version bump to 5.5.0
- Added .bookignore file to not include unnecessary directories and files for Gitbook build.

added publish script + version bump to 5.5.0

---

api/README.md
api/assets/interface-contracts/oracle-service-swagger-v1.yaml

removal of currency from payload

updating of swagger definition for oracle post participants batch

---

deployment-guide/deployment-troubleshooting.md

story https://github.com/mojaloop/helm/issues/196

Added FAQ for ingress issue

---

SUMMARY.md
contributors-guide/standards/triaging-ml-oss-bugs.md

Created two slack channels as well on Mojaloop Slack, one public and one for sensitive issues.

Documenting the proposal process on Bug triage for Mojaloop Open Source

---

mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence/seq-acct-lookup-del-participants-7.1.2.plantuml

- Changed `FSPIOP_CALLBACK_URL_PARTIES_PUT` to `FSPIOP_CALLBACK_URL_PARTICIPANT_PUT` in sequence diagram for "DEL Participants"

Fix error in ALS' sequence diagram for DEL Participants

---

mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-quotes-1.0.0.plantuml
package-lock.json
package.json

- Changed 202 response codes to 200 for PUT `/quotes/{ID}` and PUT `/quotes/{ID}/error` endpoints

Fix PUT response codes for quoting service

---

contributors-guide/standards/versioning.md

- Note on versioning for new proposal to use only SemVer from PI11 onwards and remove PI/Sprint dependency
- PI-10 schedule change and Sprints

Note on versioning & PI-10 schedule change

---

SUMMARY.md
discussions/decimal.md
package.json

- "Moajoop" => "Mojaloop" in decimal.md.
- gitbook index reference "Moajoop" => "Mojaloop".
- Updated version to 10.1.0.

Corrected typo "Moajoop" => "Mojaloop" in decimal.md and gitbook index.

---

meeting-notes/da-notes.md

Please review and incorporate for the next release of the documentation

Updated DA Meeting notes with latest decisions

---

deployment-guide/README.md

as it does not seem to be required, unless I'm missing something.. but why would you have to run Helm as root?!
The only reference I could find to this was https://github.com/helm/helm/issues/4216.
If it IS required for a good reason, then perhaps we could update the doc to clarify?
PS: I'm still working through the installation, just contributing to update docs as I go along.

remove sudo helm from Deployment Guide

---

deployment-guide/README.md

see https://github.com/mojaloop/helm/issues/347
Or is this wrong and it really depends on the version of the Helm chart? Then the required and supported Kubernetes and Helm versions could be clarified better in some sort of table of Mojaloop => Kubernetes + Helm versions... I've kept this simple based on what I've just learnt works for the current default installation.

Clarify that (currently) Kubernetes 1.15.x and Helm v2.x are required

---

meeting-notes/da-notes.md

Updated DA Meeting notes with the discussion on Issue 51

Updated DA Meeting notes

---

SUMMARY.md
mojaloop-technical-overview/quoting-service/README.md
mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-get-bulk-quotes-2.1.0.plantuml
mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-get-quotes-1.1.0.plantuml
mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-post-bulk-quotes-2.2.0.plantuml
mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-post-quotes-1.2.0.plantuml
mojaloop-technical-overview/quoting-service/assets/diagrams/sequence/seq-quotes-overview-1.0.0.plantuml
mojaloop-technical-overview/quoting-service/qs-get-bulk-quotes.md
mojaloop-technical-overview/quoting-service/qs-get-quotes.md
mojaloop-technical-overview/quoting-service/qs-post-bulk-quotes.md
mojaloop-technical-overview/quoting-service/qs-post-quotes.md

Adding sequence diagrams for
- POST /bulkQuotes
- PUT /bulkQuotes/{ID}
- PUT /bulkQuotes/{ID}/error
- GET /bulkQuotes
Posted snapshots below to help with reviews

Adding sequence diagrams for bulk Quotes

---

deployment-guide/README.md

Both HTTP and HTTPS are available for the Mojaloop Helm repo, so let's recommend everyone uses the HTTPS option.

Updated mojaloop helm repo from http to https

---

contributors-guide/standards/creating-new-features.md

Part of /mojaloop/design-authority#71

feat: add pr titles to coding standards

---

deployment-guide/README.md

Fix for this -> https://helm.sh/blog/new-location-stable-incubator-charts/

chore: new location for stable and incubator charts

---

contributors-guide/standards/versioning.md

chore: note on package versions below v11.0.0

---

deployment-guide/README.md

- include supported k8s versions for v13.0 release
- removed patch versions from supported k8s versions

docs: updating deployment guide

---

vuepress/docs/.vuepress/config.js
vuepress/docs/api/fspiop/use-cases.md

- Migrated the `Use Case` documentation.
- Created sidebar config for `Use Case` documentation.
- Fixed typos and made grammatical corrections.
- Replaced numbered headers and sub-headers with named headers. e.g. `## 4.1 ABC` to `## ABC` to allow for ease of modification.
- Restructured document structure and moved `List of Tables` to the end of the documentation.
- Added table links so that they point to the tables themselves not the section in which they are contained.
Screenshot of `Use Cases` documentation:

feat: migrated and restructured use case docs, updated sidebar config

---

vuepress/docs/.vuepress/config.js

Enables the "edit on github" link on the bottom of pages. 
Notes:
- We will need to update the branch to `master` when we do the merge back in.
- I noticed that I had to select the "next" version of the documentation link to work, and not get a 404 when redirecting to GitHub. So perhaps we should find a way to disable the edit button when users are browsing previous versions of the documentation.

feat: enable edit on github link

---

vuepress/docs/api/fspiop/json-binding-rules.md
vuepress/docs/api/fspiop/pki-best-practices.md
vuepress/docs/api/fspiop/scheme-rules.md
vuepress/docs/api/fspiop/v1.1/encryption.md
vuepress/docs/api/fspiop/v1.1/signature.md

- Updated links on all FFSPIOP API specification docs.
- Added missing `Open API for FSP Interoperability Specification` section on `Encryption`  and `Signature` docs.
- Updated  `Open API for FSP Interoperability Specification` section to point to links for `JSON Binding Rules`, `Scheme Rules` and `PKI Best Practices` docs.

chore: updated links onFSPIOP API docs

---

infra/src/cloudfront.tf

For some reason, `https://mojaloop.io/helm/repo/` redirects to `https://docs.mojaloop.io/helm/repo` which is now broken because of the docs updates.
This change adds the necessary cloudfront config to point that link to where the charts are published on github pages

feat(infra): add /helm/ path to cloudfront

---

.circleci/config.yml
CODEOWNERS
docs/.vuepress/config.js
package-lock.json
package.json

minor fix: removing a broken link on the thirdparty transaction-patterns as it doesn't need a link; it has two sub-items and it is collapsible, so removing link (and also on older versions under FSPIOP, which has a similar issue)

fix: removing broken link

---

docs/community/contributing/new-contributor-checklist.md

Changing links from mojaloop.io to docs.mojaloop.io along with new paths.

docs: update links for creating new features

---

docs/getting-started/technical-faqs.md

In the section 24 of the Technical FAQ page, I added an instruction for people using kubectl command line, instead of Kubernetes dashboard.

feat: add CLI based instruction in Technical FAQ - section 24

---

docs/community/standards/creating-new-features.md

This PR includes more details about branching and also is a proposal to introduce pre-release patterns for branches that will allow us to automate further the development process. Currently automation for publishing of pre-release versions is only available for a limited pattern `-snapshot.x`, which creates conflicts when multiple features or fixes need to be developed in isolation and pre-released for testing. As many of these features or fixes will branch from the same commit in main, they end up having the same snapshot versions/tags. The proposal is to have arbitrary names of these prereleases and trigger the publishing based on the branch name, instead of the tag name, while the tag naming will be automated.

docs: pre-release branches

---

docs/product/features/CrossBorder.md
docs/product/features/ForeignExchange.md
docs/product/features/InterconnectingSchemes.md
docs/product/features/connectivity.md
docs/product/features/engineering.md
docs/product/features/invariants.md
docs/product/features/ml-feature-list.md
docs/product/features/product.md
docs/product/features/risk.md
docs/product/features/transaction.md
docs/product/features/use-cases.md

Updated the Product docs to include a version history (at the bottom), and an indication of the version of Mojaloop they apply to.

docs: add change history and Mojaloop version details to Product documentation

---

docs/product/features/deploying.md

This should fix the broken links in the deployment tools page

Added missing .html to tools link

---

.circleci/config.yml

Should prevent circleci from running the build_and_test workflow on the schedule.

fix: don't run main workflow on the schedule

---

docs/community/standards/triaging-bugs.md

chore: update bug triage steps to clear outdated info

chore: update bug triage steps to clear outdated info
