mojaloop/documentation

Dockerfile, package-lock.json, package.json
- cause was due to the WORKDIR being set incorrectly in the Dockerfile
- also bumping up version to 5.4.3
=> Fixing UML issue

book.json, mojaloop-technical-overview/account-lookup-service/als-get-participants.md, mojaloop-technical-overview/account-lookup-service/als-get-parties.md, mojaloop-technical-overview/account-lookup-service/als-post-participants.md, package-lock.json, package.json
Changed the UML generated for PlantUML so that links may work correctly when rendering within a Markdown page.
=> Hotfix for UML links to work correctly

SUMMARY.md, package-lock.json, package.json
1. It is showing the incorrect change-log from gh-pages and not master
2. It takes way too long to render
=> Disabling change-log for a couple of reasons:

book_variables.yml
Updating version variable to 1.1 for Oracle API Specification.
=> Updating ALS Config vars to match the API version

Discussions/README.md
needs to be reviewed and updated as per discussions
=> updates based on integration document

SUMMARY.md, onboarding.md
Recreation of this [closed PR](https://github.com/mojaloop/documentation/pull/71) because the original fork was deleted.
=> Creating an onboarding section, with the purpose of presenting a list of assets at a glance for newcomers.

package-lock.json, package.json
Fix to resolve the current build issue by rolling back the `gitbook-plugin-uml version` dependency for the time being.
=> updated package-lock

contributors-guide/standards/creating-new-features.md, deployment-guide/README.md, package-lock.json
I updated the kubernetes dashboard link and also noticed the version in package-lock.json for gitbook-plugin-uml was out of sync with package.json.
=> Fixed kubernetes dashboard link

deployment-guide/README.md
Current version redirects to https://etcd.io.
=> Update etcd link

mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-position-1.3.0.plantuml, mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-position-1.3.1-prepare.plantuml, mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.0.plantuml, mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.1.a.plantuml
to 'single transfer' SDs instead of them having the additional complexity of the bulk transfer related steps. [The SDs under bulk transfers have bulk transfer related steps that are extensions of these]
=> Reverting the sequence diagrams under central-ledger

contributors-guide/standards/versioning.md
- Open bug: https://github.com/mojaloop/project/issues/856
=> Fixing link for latest releases

repositories/README.md
- part of: https://github.com/mojaloop/project/issues/948
=> Add a list of mojaloop repos in categories

onboarding.md
- Remove references to deprecated repos in the onboarding section
- Update onboarding section with more relevant information about the sdk-scheme-adapter and api library
Part of: https://github.com/mojaloop/project/issues/948
=> Remove references to deprecated repos in the onboarding section

.circleci/config.yml, .ncurc.json, mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.4.a.plantuml, onboarding.md, package-lock.json, package.json
Related issue: https://github.com/mojaloop/project/issues/700
- Add section to show conditional notification back to Payee DFSP
- Update dependencies
=> Update sequence diagram for transfers based on #700

mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-1.1.1-bulk-prepare-handler.plantuml, mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-2.1.1-bulk-fulfil-handler.plantuml, mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-2.2.1-fulfil-handler-commit.plantuml, mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-2.3.1-position-fulfil.plantuml, mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-3.1.1-timeout-handler.plantuml
- Post implementation docs update
=> feature/749 Bulk Transfers Timeout (2)

package-lock.json, package.json
- Downgrade gitbook-plugin-uml to v1.0.1
=> hotfix/Downgrade Gitbook UML Plugin

deployment-guide/deployment-troubleshooting.md
- Added a how-to-fix a common connectivity issue when using microk8s
=> Update deployment-troubleshooting.md with microk8s connectivity issue 

SUMMARY.md, discussions/decimal.md, mojaloop-publications.md, package-lock.json, package.json
- Bumped package.json version for next release
- Fixed some linting and formatting issues with Decimal.md document
- Added missing navigation items for all discussion documentation <-- this is required for Gitbooks to properly process them from MD format into HTML for web rendering.
=> Update version for new release.

contributors-guide/standards/versioning.md, deployment-guide/releases.md
=> Add sprint schedule to versioning

contributors-guide/frequently-asked-questions.md
Changed from `Increased RAM to 24 MB` to `Increased RAM to 24 GB`
=> Fixed typo

contributors-guide/README.md, repositories/README.md
- Help new users find the repo overview by adding a link to it in the Contributor's Guide
=> Make it easier to find the repo overview

mojaloop-technical-overview/event-framework/README.md
=> Minor typo

contributors-guide/tools-and-technologies/aws-cli.md
This is a short doc describing my setup for using the `aws cli` with MFA enabled.
This probably belongs somewhere else, but I wanted to capture it while it was on the top of my head.
=> Add doc about cli access with aws mfa

deployment-guide/releases.md
Updated two of the latest releases
=> Updated two of the latest releases

meeting-notes/scrum-of-scrum-notes.md
( I missed a few notes unfortunately :-) ).. If you have them, please post in the comments here and I'll make the changes
=> Notes from the meeting on April 16th 

mojaloop-roadmap.md
=> updated roadmap

meeting-notes/scrum-of-scrum-notes.md
scrum-of-scrum meeting notes from meeting on May 7th
=> Update with notes from meeting on May 7th

deployment-guide/README.md
Add mapping from 127.0.0.1 to transaction-request-service.local to enable the passing of test cases in postman calling the transaction-request-service.
=> Add transaction-request-service.local to /etc/hosts config

mojaloop-technical-overview/central-ledger/README.md
Added headings to v1.0, v1.1 arch diagrams
=> Added headings to v1.0, v1.1 arch diagrams

CODEOWNERS
updating ID in code-owners :-) , thanks for approving (in advance)
=> updating ID in code-owners

meeting-notes/da-notes.md
Added minutes for the DA meeting held on 8 July 2020
=> DA Minutes Update

contributors-guide/standards/versioning.md
adding Sprint schedule for PI-11
=> Sprint schedule for PI-11

contributors-guide/standards/versioning.md
Providing versioning guidance for PI-11 and beyond
=> Providing versioning guidance for PI-11 and beyond

mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-reject-2.2.0-v1.1.plantuml, mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer-v1.1.md, mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer.md, package-lock.json, package.json
- Fix errors with transfer reject/abort diagrams. 
- Mark v1.0 SD for transfer reject/abort sequence as `Outdated`
=> #1634: Fixes for Transfer Reject/Abort sequence diagrams and page

contributors-guide/standards/versioning.md
=> Sprint schedule for PI-12

contributors-guide/frequently-asked-questions.md, deployment-guide/README.md, deployment-guide/deployment-troubleshooting.md, deployment-guide/local-setup-linux.md, deployment-guide/local-setup-mac.md, deployment-guide/local-setup-windows.md, package-lock.json
- General
- Fixed markdown lint issues
- Removed duplicated content from platform-specific deployment guides to main deployment guide
- Updates to Troubleshooting 
- Removed non-applicable issues
- Updates to existing issues to make them relevant around the NGinx Ingress controller version
- Moved a development issue to the FAQ under the contribution guide
- Updates to Mac, Linux & Window Setup guides
- Fixed broken links to the main deployment guide
- Removed  Ingress Controller setup and moved that to the main guide (except for Linux which uses micok8s and has specific instructions)
- Updated links/section to the applicable "official" documentation for installing components (snapd, microk8s, docker, etc)
- Added "sudo" to Linux guide commands
- Updated main deployment guide to reference …
=> fix(#2265): validating a mojaloop deployment as described in the documentation is failing

contributors-guide/tools-and-technologies/automated-testing.md
as we use TTK and TTK based Golden path test collections now
=> fix: updating postman test instructions as deprecated

deployment-guide/README.md
Adds a third party section to the existing deployment guide
=> feat(mojaloop/project#2533): third party deployment guide

README.md, contributing-guide.md
- Added initial version of contributing guide to project
=> feat: added initial version of contributing guide to project

vuepress/docs/api/settlement/README.md
- Migrated the `Settlement API` documentation.
TBD:  Configuring vuepress to render Swagger specifications.
=> feat: migrated settlement api documentation

vuepress/docs/.vuepress/config.js, vuepress/docs/api/fspiop/glossary.md
- Migrated FSPIOP API Glossary docs
=> feat: migrated api spec glossary page

docs/.vuepress/config.js, docs/.vuepress/theme/components/Footer.vue, docs/.vuepress/theme/components/PageEdit.vue, docs/api/README.md, docs/api/fspiop/README.md, docs/api/fspiop/definitions.md, docs/api/fspiop/generic-transaction-patterns.md, docs/api/fspiop/glossary.md, docs/api/fspiop/json-binding-rules.md, docs/api/fspiop/logical-data-model.md, docs/api/fspiop/pki-best-practices.md, docs/api/fspiop/scheme-rules.md, docs/api/fspiop/use-cases.md, docs/api/fspiop/v1.1/api-definition.md, docs/api/fspiop/v1.1/encryption.md, docs/api/fspiop/v1.1/signature.md, docs/api/license.md, docs/api/thirdparty/transaction-patterns-linking.md, docs/getting-started/license.md
- fix(svg): images not rendering in api specification
- feat(license): add license footers and text
- fix(link): edit page on github broken link
=> fix: misc docs fixes

docs/technical/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-3.1.0-timeout-overview.plantuml, docs/technical/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-3.1.0-timeout-overview.svg, docs/technical/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-3.1.1-timeout-handler.plantuml, docs/technical/central-bulk-transfers/assets/diagrams/sequence/seq-bulk-3.1.1-timeout-handler.svg
chore(mojaloop#2882):  update bulk transfer timeout seq diagrams - [https://github.com/mojaloop/project/issues/2882](https://github.com/mojaloop/project/issues/2882)
- Updated payload to 3303 error used in implementation in diagram
- Update overview seq diagram with callback examples from the bulk-api-adapter
=> chore(mojaloop#2882): update bulk transfer timeout seq diagrams

docs/technical/sdk-scheme-adapter/BulkEnhancements/SDKBulk-API-Design.md, docs/technical/sdk-scheme-adapter/BulkEnhancements/SDKBulk-Tests.md, package-lock.json, package.json
chore:
Updated the testing documentation to align with the test updates and results.
=> chore: Update Testing Documentation

legacy/deployment-guide/README.md
feat(mojaloop/#2975): mojaloop helm release v14.1.0 - mojaloop/project#2975
=> feat(mojaloop/#2975): mojaloop helm release v14.1.0

docs/api/administration/README.md
- vuepress is not parsing the link correctly, by adding the `.md` suffix, it will be handled correctly.
=> fix: admin api link not opening first time

docs/api/thirdparty/README.md, website/versioned_docs/v1.0.1/api/thirdparty/README.md
https://docs.mojaloop.io/api/thirdparty/#api-definitions
=> fix: (rfc)(doc-3334)replaced links w github

docs/community/mojaloop-roadmap.md
Updated the roadmap page on the Mojaloop website to reflect the changes agreed at the PI 23 Convening.
=> Mojaloop Roadmap PI 23

CODEOWNERS, docs/community/mojaloop-roadmap.md, package-lock.json, package.json
format fixes, code owners list change
=> chore: format fixes, code owners list change

docs/adoption/index.md
chore: update index md description
=> chore: update index md description

docs/technical/central-fx-transfers/transfers/README.md
=> chore: minor editorial fix

docs/.vuepress/config.js, docs/product/README.md, docs/product/features/connectivity.md, docs/product/features/fx.md, docs/product/features/interscheme.md, docs/product/features/iso20022.md, docs/product/features/merchant-payments.md, docs/product/features/ml-feature-list OLD.md, docs/product/features/transactions.md, docs/product/features/use-cases.md
Added space for FX, interscheme, merchant payments and ISO 2002 (just stubs for now)
Moved the use case documentation into its own file; then restructured and extended the use case documentation
Updated the transactions documentation accordingly, and made space for ISO 20022
Improved the Product Documentation Readme
=> Updated Product feature List documentation

docs/product/features/connectivity.md, docs/product/features/engineering.md, docs/product/features/fx.md, docs/product/features/interscheme.md, docs/product/features/invariants.md, docs/product/features/iso20022.md, docs/product/features/merchant-payments.md, docs/product/features/ml-feature-list.md, docs/product/features/product.md, docs/product/features/risk.md, docs/product/features/transaction.md, docs/product/features/use-cases.md
chore: reverting paul's changes for product folder
=> chore: reverting pauls changes

docs/.vuepress/config.js
Changed the sidebar menu items to match the landing document contents/links.
=> chore: changed config.js to reflect the desired sidebar elements

docs/product/features/ml-feature-list.md, docs/product/features/product.md
Proper use of bold on landing page.
Updated Product page to refer to Portals, as was originally intended.
=> Cosmetic changes in landing page and portals

docs/.vuepress/config.js, docs/product/features/product.md, docs/product/features/use-cases.md
Use case document needed more explanation about merchant payments.
Portals document - just fixed a typo. Portal -> Portals.
Also fixed an incorrect label in the sidebar.
=> chore: typos fixed in use cases and portals; also fixed sidebar

docs/.vuepress/config.js, docs/technical/technical/deployment-guide/nodejs-dependency-update-guide.md
Create documentation containing the sequence on which to update the libraries contained in a Mojaloop release for future easier maintenance.
=> feat: add repo update sequence doc

docs/.vuepress/config.js, docs/technical/technical/deployment-guide/mojaloop-repository-update-guide.md, docs/technical/technical/deployment-guide/nodejs-dependency-update-guide.md, package-lock.json, package.json
Changes in PR:
-configure vuepress-plugin-mermaidjs to be able to display mermaid diagrams from .md
-update description on new doc webpage from nodejs dependency to mojaloop repository
=> feat: configure vuepress-plugin-mermaidjs

.circleci/config.yml, infra/state/terraform.tfstate, infra/state/terraform.tfstate.backup_dep, infra/state/terraform.tfstate_dep
Latest version from here: https://releases.hashicorp.com/terraform
This is needed to allow the `import`  ability needed by #492
=> Update TF to latest version

docs/.vuepress/config.js, docs/product/features/deploying.md, docs/product/features/tools.md
This is a first pass the tool landing page. (It also includes a small fix that changed the style of other tables)
Created a new section in the product area for the tools content but let me know if this needs to be moved.
Also includes a pass at having better written content in the tools rather than the bullet points in the deploying tables. Also let me know if this needs tweaking.
=> Tool landing page

infra/src/cloudfront.tf
=> fix(cloudfront): add function association to PR preview paths

.circleci/config.yml
Turns out I misread the documentation for this
=> fix: schedule pipeline fix

docs/product/features/use-cases.md
Added a description of e-commerce payments using RTP. Retitled 3PPI payments as Fintech payments. Clarified bulk payment initiation via 3PPI. Finally, some cosmetic updates to highlight hyperlinks to other documents.
=> docs: added an entry for e-commerce, emphasised fintechs, clarified bulk payments, some cosmetic updates.

docs/product/features/security.md
Added a "Maintaining Security" section, which summarises Sam's more technical documentation, and links to that documentation for those who need further detail.
=> Added "Maintaining Security"

docs/product/features/ml-feature-list.md, package-lock.json, package.json
Added a new section detailing the regulators' and operators' perspective, including onboarding, risk management, settlement models, and indirect participation. Improved document structure and clarified technical and ecosystem descriptions for Mojaloop.
=> Expand ML feature list with operator perspective

scripts/_deploy_preview_s3.sh
Should show images on previews now
=> fix: copy over nested assets

docs/technical/business-operations-framework/SecurityBC.md
Fixing two tables for formatting issues
=> docs: fix formatting issues in securitybc md

docs/product/features/security.md, package-lock.json, package.json
Added a new section to the security documentation explaining the security benefits of open source software and Mojaloop's reliance on open, peer-reviewed cryptographic algorithms. Clarified that Mojaloop's security model is multi-layered and does not depend on obscurity.
=> Expand security documentation on open source principles
